### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by RikiRat** [KartoffelChipss/LifeStealZ#13]
All in-game commands related to this plugins most recent version don't work

**Comment by RikiRat** [comment]
What do you mean by server software? Like spigot, paper, etc?
Minecraft version 1.21
plugin version 1.1.21
No error messages but everytime i type a command in-game nothing at all happens

**Comment by KartoffelChipss** [comment]
Spigot and PaperMC would be examples of server software, yes.
If you say no error message, you also mean no error message in the console?
And if you do `/pl` is the plugin green or red?

**Comment by RikiRat** [comment]
The console just says i used a command but nothing about the command or any error messages or anything. Its basically like i never used it.
When i use /pl is comes out green.

**Comment by RikiRat** [comment]
Im also using Spigot

**Comment by KartoffelChipss** [comment]
You need to use PaperMC

**Comment by RikiRat** [comment]
So the plugin doesnt work for spigot rn?

**Comment by KartoffelChipss** [comment]
It never did

**Comment by RikiRat** [comment]
Oh, in the loaders it shows spigot but thanks anyway.
