### ISSUE TITLE
java.lang.NoClassDefFoundError: org/bstats/bukkit/Metrics

### ISSUE THREAD

**Issue by EmanYm** [KartoffelChipss/LifeStealZ#16]
**Describe the bug**
LifeStealz is having issues during server startup.  Something about metrics

**To Reproduce**
1. Server version: Purpur 1.20.6 build 2227
2. LifeStealz version: 1.1.22 downloaded from Modrinth
3. Start server

**Expected behavior**
This line is always weird to me, I expected to not get an error. 😆 

**Screenshots**
No screenshots, but I do have an [mclog](https://mclo.gs/x519wcf) with all of the other stuff removed, and a copy of [my config](https://mclo.gs/hgvkHoJ) with the database stuff removed

**Server Setup**
 - Server Software: `This server is running Purpur version 1.20.6-2227-ver/1.20.6@79d199c (2024-06-04T23:20:38Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)`
 - Plugin Version `[LifeStealZ] Loading server plugin LifeStealZ v1.1.22`

**Additional context**
I can provide an unedited latest.log if you think it's required.

**Edit**
It still [crashes the plugin](https://mclo.gs/GJJqJE4) even when LifeStealz is the only plugin being loaded.

**Comment by abb3v** [comment]
Can you try using version 1.1.21. I speculate something has occured in latest build.

**Comment by EmanYm** [comment]
Sorry, I got distracted by house hunting...
Here is the new [latest.log](https://mclo.gs/P3E8zsD) with LifeStealz 1.1.21

**Comment by abb3v** [comment]
I'll inspect this shortly. For now, use version 1.1.21

**Comment by EmanYm** [comment]
The issue may be with bStats, and not LifeStealz
I'm getting an error from multiple plugins that has a 429 (too may requests) error code when trying to reach https://bStats.org/api/v2/data/bukkit

**Comment by KartoffelChipss** [comment]
Does this errot still ocurr?

**Comment by EmanYm** [comment]
Let me turn bStats back on and switch to 1.1.22...

**Comment by KartoffelChipss** [comment]
This should be resolved with  [1.1.22](https://github.com/KartoffelChipss/LifeStealZ/releases/tag/1.1.22).

**Comment by EmanYm** [comment]
Confirmed, The version you linked with bStats enabled does **not** crash the plugin on server start.
