### ISSUE TITLE
How to do placeholerapi?

### ISSUE THREAD

**Issue by Ghalbeyou** [KartoffelChipss/LifeStealZ#18]
I am using paper 1.21. I need to show hearts of the player in the board. I use placeholderapi but I couldn't find the extension of LifestealZ on that.

**Comment by MaCCrafter** [comment]
This is not a bug so please use the Discord server next time. The placeholder you’re looking for is `%lifestealz_hearts%`. Next time you could have a look at the official docs https://lsz.strassburger.dev/.

**Comment by Ghalbeyou** [comment]
Well.. That placeholder doesn't work and is not registered.

**Comment by KartoffelChipss** [comment]
What version of PlaceholderAPI are you using?

**Comment by KartoffelChipss** [comment]
I'll mark this as solved then. For any support related stuff, please use the [Discord](https://strassburger.org/discord).
