### ISSUE TITLE
Players with minimum hearts still give hearts to the killer, allowing infinite heart farming.

### ISSUE THREAD

**Issue by xLevitate** [KartoffelChipss/LifeStealZ#29]
**Describe the bug**

**To Reproduce**
1. Kill players with minimum amount of hearts

**Expected behavior**
They should not drop/give hearts to the killer, as that causes issues.

**Screenshots**

**Server Setup**
 - Server Software: Pufferfish
 - Minecraft Version 1.20.1
 - Plugin Version 2.4.0

**Additional context**

**Comment by KartoffelChipss** [comment]
If I understand you correctly, you are saying that when you kill a player that has one heart (let's say that's the minimum) left, the killer should not gain a heart. But why? The killer killed someone so he "stole" their heart and the other player is eliminated and has to be revived again by someone else. I don't see how you could farm infinite hearts. 

Maybe the crafting recipe for the revive crystal is so easy that players can craft them in masses. Then just set the crafting recipe to something harder.

If you have set `disablePlayerBanOnElimination ` to `true` either make your custom commands punish a player harder or set `heartRewardOnElimination` to `false `

**Comment by KartoffelChipss** [comment]
I guess this is resolved

**Comment by xLevitate** [comment]
> If I understand you correctly, you are saying that when you kill a player that has one heart (let's say that's the minimum) left, the killer should not gain a heart. But why? The killer killed someone so he "stole" their heart and the other player is eliminated and has to be revived again by someone else. I don't see how you could farm infinite hearts.
> 
> Maybe the crafting recipe for the revive crystal is so easy that players can craft them in masses. Then just set the crafting recipe to something harder.
> 
> If you have set `disablePlayerBanOnElimination ` to `true` either make your custom commands punish a player harder or set `heartRewardOnElimination` to `false `

In this case I'm not using any sort of elimination system on my server, so the player doesn't get eliminated, they just respawn at 1 heart and can be killed again, over and over.

**Comment by KartoffelChipss** [comment]
duh, you would only want to set `disablePlayerBanOnElimination ` to true if you implement your own banning system...

**Comment by xLevitate** [comment]
> duh, you would only want to set `disablePlayerBanOnElimination ` to true if you implement your own banning system...

I have a more friendly server so I don't want to eliminate players in any way, but I also don't want them to be able to give hearts if they are at the minimum. I suppose I will just switch to LifestealCore to fix my issue.

**Comment by KartoffelChipss** [comment]
If LifeStealCore fits your server better, go for it. I don't mind.

But you are saying that you don't want players to get eliminated or implement your own banning system but at the same time you are complaining that people don't get punished enough for loosing all their hearts. You cannot have both at the same time.
And if you don't want players to loose hearts at all, why are you using a **LifeSteal** plugin at all?
This makes no sense at all...

**Comment by KartoffelChipss** [comment]
I don't think you understand what I'm trying to say or understand the concept of LifeStealZ. I will lock this issue now as this has nothing to do with LifeSteal. If LifeSteal core works for you, please just use that plugin
