### ISSUE TITLE
I cannot run the plugin.

### ISSUE THREAD

**Issue by PizzaGod873** [KartoffelChipss/LifeStealZ#36]
**Describe the bug**
The best I can explain it is, it is saying it needs to be updated and getting a lot of errors.

**To Reproduce**
Not really sure, but I'll do the best I can. Comment if you need more info.
My plugins are: ViaVersion, floodgate, ViaBackwards, LuckPerms, Geyser-Spigot, LifeStealZ, Vault, Essentials, EssentialsSpawn, EssentialsChat

**Expected behavior**
To run normally.

**Screenshots**
[Logs](https://mclo.gs/wiiMqLB)

**Server Setup**
 - Server Software: [SpigotMC]
 - Minecraft Version [1.21.1]
 - Plugin Version [2.7.2]

**Additional context**
Again, here are the [Logs](https://mclo.gs/wiiMqLB)

**Comment by Zanguz** [comment]
Hello! The same error happened to me! I'm using mc 1.20, and tried using the plugin 2.7.2, 2.7.1 and 2.7.0 but got the same error each time. The weird part is that the plugin seems to be enabled and working when checking with the /pl command, but it doesn't actually work. I also get the same error log.

![image](https://github.com/user-attachments/assets/4896662f-2b59-4f69-879f-1739e5fe4a9d)

**Comment by KartoffelChipss** [comment]
You need to use PaperMC or any fork of PaperMC.
If you need additional support, please use the [Discord](https://strassburger.org/discord). This is only for bugs or Feature Requests.
