### ISSUE TITLE
Just wondering, how do the permissions work?

### ISSUE THREAD

**Issue by DDAN-17** [KartoffelChipss/LifeStealZ#7]

**Comment by KartoffelChipss** [comment]
What exactly do you mean by that? Could you elaborate on that?

**Comment by DDAN-17** [comment]
On the Readme, there's a section about permissions, but how do you actually manage the permissions for a server?

**Comment by Hecker-01** [comment]
@DDAN-17 use luckperms

**Comment by KartoffelChipss** [comment]
As @DDAN-17 said, you can manage permissions using a plugin like Luckperms, but this is not really an Issue related to LifeStealZ
